name: 808HAL
favicon: null
layout_spectrum: 0.22751
typography_spectrum: 0.83833
title: Harold at Large
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5b90b0'
    - '#004735'
    - '#94b6ca'
    - '#c6dbe6'
  brandStrength: 0.31467225728556514
  lightness: 0.5331257858779281
  saturation: 0.08822554023936391
  rhythmicContrast: 0.5920760496519506
purpose: []
