name: 808HAL
favicon: null
layout_spectrum: 0.75102
typography_spectrum: 0.83833
title: Harold at Large
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4d2ed'
    - '#395190'
    - '#6586bb'
    - '#201e1f'
    - '#a59165'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
